### ISSUE TITLE
Show score in icon instead of badge

### ISSUE THREAD

**Issue by ghost** [Politiwatch/PrivacySpy-Extension#1]
As a score should ideally be shown in most websites, I think that the score should be shown in the toolbar icon rather than a badge. I think that the badge is only useful when a badge it isn't normally displayed, or if the badge indicates something else. Perhaps the active warning ! badge could be continued, and display on top of a score in the toolbar icon.

An example of this in another extension is the DuckDuckGo Privacy Essentials which shows a letter grade in it's toolbar icon (shown in image below).

<img width="63" alt="Screen Shot 2019-09-20 at 3 03 57 PM" src="https://user-images.githubusercontent.com/53424460/65297076-c6f73300-dbba-11e9-92be-7d96096eb952.png">

**Comment by milesmcc** [comment]
This is a good suggestion; we will see if we can include something like this for version 2.0.

**Comment by doamatto** [comment]
Looks like this was added, which means this should be good to close :smile:
![image](https://user-images.githubusercontent.com/30969346/85047609-ec639e00-b146-11ea-921f-159c7a0958d8.png)
